services:
  - type: web
    name: healthnest-api
    runtime: docker
    dockerfilePath: ./backend/HealthNest.Api/Dockerfile
    dockerContext: ./backend/HealthNest.Api
    plan: free
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: healthnest-db
          property: connectionString
      - key: Jwt__Issuer
        value: SirZaeem.HealthNest
      - key: Jwt__Audience
        value: SirZaeem.HealthNest.Client
      - key: Jwt__Key
        generateValue: true
      - key: AllowedOrigins__0
        sync: false
      - key: Gemini__ApiKey
        sync: false
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

databases:
  - name: healthnest-db
    plan: free
    databaseName: healthnestdb
    user: healthnest
